version: '3.8'

services:
  mysql:
    container_name: mysql_server
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vidkeeper_db
      MYSQL_USER: appuser          # Create appuser
      MYSQL_PASSWORD: apppass      # Set password for appuser
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - spring-ms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass  # Should match the MYSQL_ROOT_PASSWORD
    ports:
      - "8071:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-ms



networks:
  spring-ms:
    driver: bridge

volumes:
  mysql_data:
